/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-1`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-4`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-5`; params?: Router.UnknownInputParams; } | { pathname: `/events`; params?: Router.UnknownInputParams; } | { pathname: `/events/archived`; params?: Router.UnknownInputParams; } | { pathname: `/stress`; params?: Router.UnknownInputParams; } | { pathname: `/stress/history`; params?: Router.UnknownInputParams; } | { pathname: `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `/events/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/new-event/step-1`; params?: Router.UnknownOutputParams; } | { pathname: `/new-event/step-2`; params?: Router.UnknownOutputParams; } | { pathname: `/new-event/step-3`; params?: Router.UnknownOutputParams; } | { pathname: `/new-event/step-4`; params?: Router.UnknownOutputParams; } | { pathname: `/new-event/step-5`; params?: Router.UnknownOutputParams; } | { pathname: `/events`; params?: Router.UnknownOutputParams; } | { pathname: `/events/archived`; params?: Router.UnknownOutputParams; } | { pathname: `/stress`; params?: Router.UnknownOutputParams; } | { pathname: `/stress/history`; params?: Router.UnknownOutputParams; } | { pathname: `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `/events/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/new-event/step-1${`?${string}` | `#${string}` | ''}` | `/new-event/step-2${`?${string}` | `#${string}` | ''}` | `/new-event/step-3${`?${string}` | `#${string}` | ''}` | `/new-event/step-4${`?${string}` | `#${string}` | ''}` | `/new-event/step-5${`?${string}` | `#${string}` | ''}` | `/events${`?${string}` | `#${string}` | ''}` | `/events/archived${`?${string}` | `#${string}` | ''}` | `/stress${`?${string}` | `#${string}` | ''}` | `/stress/history${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-1`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-4`; params?: Router.UnknownInputParams; } | { pathname: `/new-event/step-5`; params?: Router.UnknownInputParams; } | { pathname: `/events`; params?: Router.UnknownInputParams; } | { pathname: `/events/archived`; params?: Router.UnknownInputParams; } | { pathname: `/stress`; params?: Router.UnknownInputParams; } | { pathname: `/stress/history`; params?: Router.UnknownInputParams; } | { pathname: `/statistics`; params?: Router.UnknownInputParams; } | `/events/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/events/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
